/** /insurance-restoration — copy, links and asset paths from the live page (checked 2026-10-07). */
import type {Block} from '@/components/blocks/Blocks'
import {book, tour} from './shared'

export const meta = {
  title: 'Insurance Claim Documentation & Estimating Tools | iGUIDE',
  description:
    'Document property damage and speed up insurance estimating with Xactimate-ready sketches, floor plans and lidar measurements. Capture once and move claims forward faster with iGUIDE.',
  path: '/insurance-restoration',
}

export const blocks: Block[] = [
  {
    type: 'hero',
    heading: 'One visit. Complete claim file.',
    subheading:
      'Capture measurements, damage tags and claim photos in a single walkthrough. Get back an estimate-ready sketch you upload straight into Xactimate.',
    ctas: [book(), {label: 'Watch a real scan', href: 'https://www.youtube.com/embed/aEh08zsWO7E?si=tNCRkBj0wKCPyGi_', variant: 'secondary', newTab: true}],
    media: {
      type: 'embed',
      src: tour('https://youriguide.com/urwkb_1121_sample_road_kitchener_on?autostart=1'),
      title: 'iGUIDE tour of a sample insurance loss, 1121 Sample Road, Kitchener ON',
    },
  },
  {
    type: 'custom',
    id: 'benefits',
    background: 'surface',
    children: (
      <div className="grid gap-8 lg:grid-cols-2 lg:gap-16">
        <h2 className="text-balance text-[32px] font-bold leading-[normal] text-ink md:text-5xl md:leading-[normal]">
          Two hours of measuring or a fifteen-minute walkthrough
        </h2>
        <div className="space-y-4 text-lg leading-7 text-body">
          <p>
            Standard documentation methods require tape, clipboards, lasers and endless manual sketches. With iGUIDE, you just walk and scan.
          </p>
          <p>
            Less time on site and no time spent building the sketch in Xactimate. You get to estimating quicker and close claims faster, with
            preliminary estimates possible on day one.
          </p>
          <p>
            Dry down spaces faster, tag moisture readings directly on site maps, and send off professional documentation to carriers so you get
            approvals faster and secure cash flow immediately.
          </p>
        </div>
      </div>
    ),
  },
  {
    type: 'featureTabs',
    id: 'watch-the-loss',
    heading: 'Watch a loss get documented end-to-end',
    subheading: 'One walkthrough, one upload and everything the estimate needs.',
    label: 'What happens on site and after',
    items: [
      {
        id: 'plan-draws-itself',
        title: 'The plan draws itself as you walk',
        text: <p>Watch the layout form on screen. Nothing gets missed and nobody drives back because a dimension was forgotten.</p>,
        media: {type: 'embed', src: 'https://www.youtube.com/embed/aEh08zsWO7E?si=vUN_Efob7KefNE-w', title: 'Watch a loss get documented end-to-end'},
      },
      {
        id: 'tag-damage',
        title: 'Tag damage where it sits',
        text: (
          <p>
            Mark moisture readings, close-up damage images and scope notes onto the floor plan while scanning. Each one pinned to its exact
            location.
          </p>
        ),
      },
      {
        id: 'pull-photos',
        title: 'Pull the photos later',
        text: <p>Take stills straight out of the 3D tour once you have left the site. Choose the exact angles you need without a second trip.</p>,
      },
      {
        id: 'upload-sketch',
        title: 'Upload the sketch to Xactimate',
        text: (
          <>
            <p>
              The finished plan comes back as an ESX file. On Premium it arrives with cabinets, bath layouts and appliances already drawn. You
              download it and import it into Xactimate.
            </p>
            <p>Your virtual tour embeds in Xactimate as well. So you can navigate the property beside the sketch while you write the estimate.</p>
          </>
        ),
      },
    ],
  },
  {
    type: 'stats',
    id: 'accuracy',
    background: 'sky',
    heading: 'Accurate enough to defend a year later',
    subheading: 'A sketch that was close enough on the day becomes a problem when the payout gets disputed.',
    stats: [
      {
        value: '0.5% distance',
        label: '1% square footage',
        text: 'Our published measurement uncertainty. Captured with a proprietary 2D LiDAR camera rather than a phone lens.',
      },
      {
        value: 'Drawn by people',
        text: 'Standard Sketch and Premium Sketch are drawn by a drafter working from the LiDAR data, not generated by AI.',
      },
      {
        value: 'The property',
        label: 'as you found it',
        text: 'A record of the condition before your crew moved anything, which is the version that matters when scope gets challenged.',
      },
    ],
  },
  {
    type: 'quote',
    quote: {
      quote:
        'Our competitors generate sketches with AI. Some run that output past a reviewer and call it human-checked. We employ drafters, and on Standard and Premium a person draws your property from the LiDAR data and turns it around inside 24 hours.',
      name: 'Roman Barrett',
      role: 'Sr. Draft Operations Manager',
      company: 'Planitar',
      photo: {src: '/assets/Testimonial-Headshots/Roman.jpeg', alt: 'photo - Roman'},
    },
  },
  {
    type: 'compare',
    id: 'compare',
    heading: 'Why we cost more than the cheaper options',
    subheading:
      "You'll hear the number and think it, so here it is directly. You're paying for accuracy you can stand behind, a sketch a person drew and no subscription sitting underneath any of it.",
    columns: {label: 'The details', ours: 'iGUIDE', theirs: 'Cheaper alternatives'},
    rows: [
      {label: 'How you pay', ours: 'Per claim, no contract', theirs: 'Monthly subscription'},
      {label: 'Slow month', ours: 'You pay less, because you pay per claim', theirs: 'You pay anyway, credits expire*'},
      {label: 'Who draws the sketch', ours: 'Our drafters, on Standard and Premium', theirs: 'AI, sometimes with a review pass'},
      {label: 'How it measures', ours: '2D professional LiDAR', theirs: 'Phone LiDAR, or none at all'},
      {label: 'Published accuracy standard', ours: 'Yes, 0.5% distance / 1% square footage', theirs: 'One level, or speed tiers only'},
      {label: 'Detail level', ours: 'Choose per claim across three tiers', theirs: 'One level, or speed tiers only'},
      {label: 'If you stop paying', ours: 'Download and self-host it indefinitely', theirs: 'Access to your documentation ends'},
    ],
    footnote: '*Some tools roll unused credits over. Most do not.',
    aside: {
      heading: 'Claim volume does not arrive monthly',
      text: 'Some months you run five jobs. After a storm you run fifty. A subscription sized to a number you cannot predict is money burned in the quiet months and a ceiling in the busy ones. You pay us per claim, so your cost tracks your work.',
    },
  },
  {
    type: 'packages',
    id: 'packages',
    background: 'surface',
    heading: 'Choose the sketch the claim actually needs',
    subheading: 'Order a different level on every job. A two-room water loss and a whole-house fire should not cost the same.',
    items: [
      {
        title: 'iGUIDE Instant Sketch',
        summary: 'Best for small, daily residential losses and preliminary estimates.',
        image: {src: '/assets/sketch.png', alt: 'iGUIDE Instant Sketch'},
        price: {label: 'Per project', value: '$24.99 USD'},
        includesLabel: 'Includes:',
        includes: [
          'Xactimate-ready sketch in minutes',
          '3D virtual tour of the loss',
          'ESX file to upload into Xactimate',
          'Every asset downloadable, including the virtual tour',
          'Upgrade to Standard or Premium later if the claim grows',
          'Outlines only. No cabinets or plumbing fixtures.',
          'Residential only, and capped at 75 scans.',
        ],
      },
      {
        title: 'iGUIDE Standard Sketch',
        summary: 'Best for residential and commercial claims.',
        image: {src: '/assets/esx_standard.png', alt: 'iGUIDE Standard Sketch'},
        price: {label: 'Starting at', value: '$64.50 USD'},
        includesLabel: 'Includes:',
        includes: [
          'Drawn by our drafting team, back within 24 hours',
          '3D virtual walkthrough of the property',
          'Colour-coded floor plans for scope review',
          'Property measurement report',
          'Outdoor features including patios and decks',
          'Every asset downloadable, including the virtual tour',
          'ESX file to upload into Xactimate',
        ],
      },
      {
        title: 'iGUIDE Premium Sketch',
        summary: 'Best for residential and commercial, when the scope needs full detail.',
        image: {src: '/assets/esx_premium.png', alt: 'iGUIDE Premium Sketch'},
        price: {label: 'Starting at', value: '$76.50 USD'},
        includesLabel: 'Includes:',
        includes: [
          'Everything in Standard Sketch',
          'Cabinets, bath layouts, appliances and fixtures drawn in',
          'Outdoor features including patios and decks',
          'Every asset downloadable, including the virtual tour',
        ],
      },
    ],
  },
  {
    type: 'quotes',
    id: 'reviews',
    heading: 'From people actually running claims',
    align: 'center',
    quotes: [
      {
        quote: 'iGUIDE technology has given Deft a huge competitive advantage... We can get through a home in probably a third of the time.',
        name: 'Jeremiah Kiefer',
        photo: {src: '/assets/iguide-vs-docusketch-jeremiah.jpg', alt: 'Jeremiah Kiefer'},
      },
      {
        quote:
          "With iGUIDE, I'm getting back at least 20 hours a week. And that's being conservative. While someone else is still hand-sketching one property, I've already done four.",
        name: 'Jeremy Murray',
        photo: {src: '/assets/Jeremy-Murray.jpg', alt: 'Jeremy Murray'},
      },
      {
        quote:
          'iGUIDE is great and the Xactimate ESX file is incredible. The amount of time saved on return trips to measure is huge savings. The camera will pay for itself. To be able to have a full sketch 24 hours later is great.',
        name: 'Chris A. Howell',
        photo: {src: '/assets/Chris-Howell.png', alt: 'Chris A. Howell'},
      },
    ],
  },
  {
    type: 'faq',
    heading: 'Frequently asked questions',
    items: [
      {
        q: 'Why does iGUIDE cost more than others?',
        a: 'Three reasons. Our published measurement uncertainty is 0.5% in distance and 1% in square footage. Standard and Premium sketches are drawn by our drafting team rather than generated. And there is no subscription underneath it, so you are not paying in the months you do not work.',
      },
      {
        q: 'Does the sketch go straight into Xactimate?',
        a: 'Not automatically. We deliver an ESX file. You download it and import it into Xactimate, which takes a moment and skips the entire redraw.',
      },
      {q: 'Do I need a subscription?', a: 'No. You buy the camera once and pay per claim after that. Nothing expires and there is no monthly minimum.'},
      {
        q: 'How long does a scan take?',
        a: 'Around 15 minutes for a typical 2,500 sq ft property. If you are coming from a phone-based AI tool, expect our capture to take a little longer, because the camera is collecting LiDAR measurements rather than estimating from photos. That is where the accuracy comes from.',
      },
      {
        q: 'Which sketch should I order for a routine water loss?',
        a: 'Instant Sketch covers daily residential water losses. Standard and Premium both handle residential and commercial, with Premium adding cabinets, baths, appliances and outdoor features. You can also upgrade an Instant Sketch to Standard or Premium later, so starting cheap does not lock you in.',
      },
      {
        q: 'What happens to my files if I stop using iGUIDE?',
        a: 'You can download the whole project, including the virtual tour, and host it yourself for as long as you like. Hosting with us is free for the first year, then a small annual fee per iGUIDE if you want us to keep it live. Either way the files are yours to pull down, which matters when a claim resurfaces years later.',
      },
      {
        q: 'Can I capture outside the building?',
        a: 'Yes, the camera works outdoors, which is useful for site context and exterior conditions. We do not sketch roofs or exterior elevations.',
      },
    ],
  },
  {
    type: 'cta',
    heading: "One visit. One complete file. Let's talk.",
    text: "Book a 15-minute product walkthrough to see how iGUIDE's IRC Bundle can pay for itself in just your first few cases.",
    ctas: [book('Book a 15-minute walkthrough')],
  },
]
